name: Test Runs

on:
    push:
        branches:
            - main

    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Updates
              run: |
                  sudo apt update
                  sudo apt install libwebkit2gtk-4.1-dev \
                    build-essential \
                    curl \
                    wget \
                    file \
                    libxdo-dev \
                    libssl-dev \
                    libayatana-appindicator3-dev \
                    librsvg2-dev \
                    libglib2.0-dev
                  # cargo install cargo-binstall
                  # cargo binstall dioxus-cli

            - name: Checkout
              uses: actions/checkout@v4

            - name: Lint
              run: cargo clippy

            - name: Test
              run: cargo test
