name: Test Runs

on:
    push:
        branches:
            - main

    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Lint
              run: cargo clippy

            - name: Test
              run: cargo test
